/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlcadasRouteImport } from './routes/alcadas'
import { Route as AprovacoesRouteImport } from './routes/aprovacoes'
import { Route as CentrosDeCustoRouteImport } from './routes/centros-de-custo'
import { Route as ConciliacaoRouteImport } from './routes/conciliacao'
import { Route as ExportacoesRouteImport } from './routes/exportacoes'
import { Route as ImportarExtratoRouteImport } from './routes/importar-extrato'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlcadasRoute = AlcadasRouteImport.update({
  id: '/alcadas',
  path: '/alcadas',
  getParentRoute: () => rootRouteImport,
} as any)
const AprovacoesRoute = AprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CentrosDeCustoRoute = CentrosDeCustoRouteImport.update({
  id: '/centros-de-custo',
  path: '/centros-de-custo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciliacaoRoute = ConciliacaoRouteImport.update({
  id: '/conciliacao',
  path: '/conciliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportacoesRoute = ExportacoesRouteImport.update({
  id: '/exportacoes',
  path: '/exportacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarExtratoRoute = ImportarExtratoRouteImport.update({
  id: '/importar-extrato',
  path: '/importar-extrato',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alcadas': typeof AlcadasRoute
  '/aprovacoes': typeof AprovacoesRoute
  '/centros-de-custo': typeof CentrosDeCustoRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/exportacoes': typeof ExportacoesRoute
  '/importar-extrato': typeof ImportarExtratoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alcadas': typeof AlcadasRoute
  '/aprovacoes': typeof AprovacoesRoute
  '/centros-de-custo': typeof CentrosDeCustoRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/exportacoes': typeof ExportacoesRoute
  '/importar-extrato': typeof ImportarExtratoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alcadas': typeof AlcadasRoute
  '/aprovacoes': typeof AprovacoesRoute
  '/centros-de-custo': typeof CentrosDeCustoRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/exportacoes': typeof ExportacoesRoute
  '/importar-extrato': typeof ImportarExtratoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alcadas'
    | '/aprovacoes'
    | '/centros-de-custo'
    | '/conciliacao'
    | '/exportacoes'
    | '/importar-extrato'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alcadas'
    | '/aprovacoes'
    | '/centros-de-custo'
    | '/conciliacao'
    | '/exportacoes'
    | '/importar-extrato'
  id:
    | '__root__'
    | '/'
    | '/alcadas'
    | '/aprovacoes'
    | '/centros-de-custo'
    | '/conciliacao'
    | '/exportacoes'
    | '/importar-extrato'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlcadasRoute: typeof AlcadasRoute
  AprovacoesRoute: typeof AprovacoesRoute
  CentrosDeCustoRoute: typeof CentrosDeCustoRoute
  ConciliacaoRoute: typeof ConciliacaoRoute
  ExportacoesRoute: typeof ExportacoesRoute
  ImportarExtratoRoute: typeof ImportarExtratoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alcadas': {
      id: '/alcadas'
      path: '/alcadas'
      fullPath: '/alcadas'
      preLoaderRoute: typeof AlcadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprovacoes': {
      id: '/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AprovacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centros-de-custo': {
      id: '/centros-de-custo'
      path: '/centros-de-custo'
      fullPath: '/centros-de-custo'
      preLoaderRoute: typeof CentrosDeCustoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conciliacao': {
      id: '/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof ConciliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exportacoes': {
      id: '/exportacoes'
      path: '/exportacoes'
      fullPath: '/exportacoes'
      preLoaderRoute: typeof ExportacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar-extrato': {
      id: '/importar-extrato'
      path: '/importar-extrato'
      fullPath: '/importar-extrato'
      preLoaderRoute: typeof ImportarExtratoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlcadasRoute: AlcadasRoute,
  AprovacoesRoute: AprovacoesRoute,
  CentrosDeCustoRoute: CentrosDeCustoRoute,
  ConciliacaoRoute: ConciliacaoRoute,
  ExportacoesRoute: ExportacoesRoute,
  ImportarExtratoRoute: ImportarExtratoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
