/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConciliacaoRouteImport } from './routes/conciliacao'
import { Route as ImportarExtratoRouteImport } from './routes/importar-extrato'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConciliacaoRoute = ConciliacaoRouteImport.update({
  id: '/conciliacao',
  path: '/conciliacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportarExtratoRoute = ImportarExtratoRouteImport.update({
  id: '/importar-extrato',
  path: '/importar-extrato',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/importar-extrato': typeof ImportarExtratoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/importar-extrato': typeof ImportarExtratoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conciliacao': typeof ConciliacaoRoute
  '/importar-extrato': typeof ImportarExtratoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/conciliacao' | '/importar-extrato'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conciliacao' | '/importar-extrato'
  id: '__root__' | '/' | '/conciliacao' | '/importar-extrato'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConciliacaoRoute: typeof ConciliacaoRoute
  ImportarExtratoRoute: typeof ImportarExtratoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conciliacao': {
      id: '/conciliacao'
      path: '/conciliacao'
      fullPath: '/conciliacao'
      preLoaderRoute: typeof ConciliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importar-extrato': {
      id: '/importar-extrato'
      path: '/importar-extrato'
      fullPath: '/importar-extrato'
      preLoaderRoute: typeof ImportarExtratoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConciliacaoRoute: ConciliacaoRoute,
  ImportarExtratoRoute: ImportarExtratoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
